DROP table if exists task.task;
DROP sequence if exists task.task_id_seq;
DROP schema if exists task;

CREATE SCHEMA task;

CREATE SEQUENCE task.task_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;


CREATE TABLE task.task (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NULL,
	description varchar(255) NULL,
	"valid" bool NULL,
	CONSTRAINT task_pkey PRIMARY KEY (id)
);